# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Jessica Li
# Description of the Site
description: Aspiring Data Analyst
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://tse3.mm.bing.net/th/id/OIP.tIYUXvalFnLfYWTArp_4PgHaFL?cb=defcache2defcache=1&rs=1&pid=ImgDetMain&o=7&rm=3

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: jessicaalbertaone.li@gmail.com
facebook_username: /
twitter_username: /
instagram_username: /
linkedin_username: Jessica Li
github_username:  Starshooter11
youtube_channel_id: 
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Jessica Li
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png
# 60 Words About the Author
author-about: "Hello! I am a student at UC Berkeley currently studying Applied Mathematics with a focus in Data Science and Computer Science. When I'm not buried under data sets, math theorems, and projects, I'm out running through the beautiful Berkeley Hills or relaxing by a window reading my favorite book."
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/Starshooter11

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

